### PR TITLE
Added model file.

### PR DESCRIPTION
**Pull request by nascarr**
Added new publisher and new model. TensorFlow 2.0 Question Answering competition at Kaggle.

### CODE REVIEW

**Comment by nascarr** [comment]
@googlebot I signed it!

**Comment by vbardiovskyg** [comment]
Hi @nascarr and thanks for your contribution!

Everything looks good -- there are just two more things:
1. Please change the publisher name to be identical to the GitHub handle (I am going to update the publishing documentation with this guideline soon).

2. Prior to accepting your pull request, we just need you to read & agree to the TensorFlow Hub terms of service at https://tfhub.dev/terms. If you feel comfortable moving forward, please add a comment "I have read and agree to the TensorFlow Hub Terms of Service" to this thread. 

After that we'll be able to accept your pull request.

Let us know if you have any questions and thanks!

**Comment by vbardiovskyg** [comment]
I edited the point (1) in the comment above, so just making sure you noticed.

**Comment by nascarr** [comment]
@googlebot I fixed it

**Comment by nascarr** [comment]
Hi @vbardiovskyg,
Thank you for the feedback!
1. It is good idea.  I changed nascar to nascarr everywhere.
2. I am going to add this comment right after this one.

**Comment by nascarr** [comment]
I have read and agree to the TensorFlow Hub Terms of Service

**Comment by vbardiovskyg** [comment]
Your model is now live: https://tfhub.dev/nascarr/nq/1, thanks for contributing!

**Comment by nascarr** [comment]
Thank you!

**Pull request closed without merging**
