### PR TITLE
New Publisher Added - Bohemian Visual Recognition Alliance

### PR DESCRIPTION
**Pull request by picekl**
Including Inception V4 model for mushroom recognition.

### CODE REVIEW

**Comment by picekl** [comment]
@googlebot I fixed it.

**Comment by picekl** [comment]
@googlebot I fixed it.

**Comment by vbardiovskyg** [comment]
Hi Lukas and thanks for contributing. There seem to be some issues with the contributions that we'll need to address before continuing.

1. Although you have agreed to CLA, the commits have likely a different e-mail address than the one used for CLA (typically one would do `git config --global user.email "email@example.com"` to set e-mail address for commits).

1. The model has to be hosted on a https location (we can't read via this drive link). Some ideas for hosting include: [GitHub release](https://help.github.com/en/enterprise/2.13/user/articles/creating-releases), [GitHub FS](https://git-lfs.github.com/), or [Google Cloud Bucket](https://cloud.google.com/storage/docs/creating-buckets).

**Comment by picekl** [comment]
Hi Vojtěch,

thank you for fast feedback.

First, the email I’m using is the same (lukaspicek@gmail.com). I will explore it more.

Second, I will use the Google Cloud Bucket <https://cloud.google.com/storage/docs/creating-buckets>. Looks good.

Lastly, I’m adding the Christine as my Google / TF Hub „contact person“.

Best,
Lukas

**Comment by picekl** [comment]
@googlebot I fixed it.

**Comment by vbardiovskyg** [comment]
Thanks for fixing the model location.

The commit e-mail now looks good to me, but I think the issue is that you have several commits and some are still from the last e-mail, so it will need some more work. I found this guide internally

> After updating GitHub configuration here, you need to follow the steps below to update author info, if you have already created commits before having properly configure .gitconfig.
> 
> 1. If only the most recent commit needs update, run: git commit --amend --reset-author
> 1. If there is more than one commit to update. Use git rebase -i.
> 1. Type e or edit on the commits you want to update.
> 1. For each commit, run: git commit --amend --reset-author and git rebase --continue
> 1. A force push to remote branch is required if you have pushed your branch before.
> 

Or alternatively you can just simply create a new PR if that's less work.

**Comment by picekl** [comment]
Looks like it passed in another pull request with squeezed commits.

LP

**Pull request closed without merging**
