### PR TITLE
doc: add link how to convert model to tfjs

### PR DESCRIPTION
**Pull request by serv-inc**

### CODE REVIEW

**Comment by arnoegw** [comment]
Hi @serv-inc, thanks for sending the pull request that references  https://stackoverflow.com/a/56084489/1587329 from retrain.py.

If I understood correctly, it asks to use an older version of TFJS to do conversion from a frozen graph pb file. However, retrain.py is also capable of exporting to SavedModel. Can that be used?

**Comment by serv-inc** [comment]
Hi @arnoegw. That was the solution given by @pyu10055 who works at google, so I though he would give the latest possible solution. Seems like my trust in Google was a bit misplaced... If you know how to do this, feel welcome to respond to either https://github.com/tensorflow/tfjs/issues/1576 or https://stackoverflow.com/questions/55849309/retrain-image-detection-with-mobilenet/56084489#56084489, I would gladly write it then. Otherwise, give me some time to check it out.

**Comment by serv-inc** [comment]
Ok, it seems like the commands

```
python retrain.py --tfhub_module https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/feature_vector/2 \
    --image_dir /tmp/flower_photos --saved_model_dir /tmp/saved_retrained_model
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model \
    --signature_name=serving_default --saved_model_tags=serve \
    /tmp/saved_retrained_model/ /tmp/converted_model/
```
produce a `model.json` file with current TFJS.

**Comment by arnoegw** [comment]
Thanks for confirming that it works with current TFJS via SavedModel! I thought it should, but I didn't really know. And thanks for posting it on StackOverflow as well.

With that clarification, what would you like to do with this pull request? There's some wisdom to be captured here, but I'm shy to add an official statement on TFJS support for retrain.py, because the TF Hub team seeks to replace it for TF2 by the much more modern [tf2_image_retraining.ipynb](https://colab.sandbox.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb). We don't want to keep looking after interoperability between retrain.py and TFJS.

How about adding general advice like:

> For deployment to other environments, `retrain.py` can be called with flag `--saved_model_dir` to export the retrained model in SavedModel format.

?

**Comment by serv-inc** [comment]
> With that clarification, what would you like to do with this pull request? There's some wisdom to be captured here, but I'm shy to add an official statement on TFJS support for retrain.py, because the TF Hub team seeks to replace it for TF2 by the much more modern [tf2_image_retraining.ipynb](https://colab.sandbox.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb). We don't want to keep looking after interoperability between retrain.py and TFJS.

Everyone would be happy if the hub-based retraining were to work. It seems like the model at least requires some tags for this.

> 
> How about adding general advice like:
> 
> > For deployment to other environments, `retrain.py` can be called with flag `--saved_model_dir` to export the retrained model in SavedModel format.

That sounds very good. Would it be ok to add a link to SO for further information as well? Like:

For deployment to other environments, `retrain.py` can be called with flag `--saved_model_dir` to export the retrained model in SavedModel format. See also [this StackOverflow answer](https://stackoverflow.com/a/56340676/1587329).

**Comment by serv-inc** [comment]
I had not tested loading the models until now. Both ways of creating fail when loaded with

> 
> 'className' and 'config' must set.
>     at new ValueError (/tmp/node_modules/@tensorflow/tfjs-layers/dist/errors.js:68:28)
>     at Object.deserializeKerasObject (/tmp/node_modules/@tensorflow/tfjs-layers/dist/utils/generic_utils.js:241:19)
>     at Object.deserialize (/tmp/node_modules/@tensorflow/tfjs-layers/dist/layers/serialization.js:29:28)
>     at /tmp/node_modules/@tensorflow/tfjs-layers/dist/models.js:290:45
>     at step (/tmp/node_modules/@tensorflow/tfjs-layers/dist/models.js:54:23)
>     at Object.next (/tmp/node_modules/@tensorflow/tfjs-layers/dist/models.js:35:53)
>     at fulfilled (/tmp/node_modules/@tensorflow/tfjs-layers/dist/models.js:26:58)
> 

so this pull request should definitely _**not be merged**_ as of now.

**Pull request closed without merging**
