### PR TITLE
check gcs bucket in load_module_spec

### LINKED ISSUE #261: Freeze when cache directory is not found
When we try to use not existing GCS Bucket, it does not occur error but freeze.
For example you can reproduce the problem running the code below:

```python
import os
import tensorflow_hub as hub

os.environ['TFHUB_CACHE_DIR'] = 'gs://this-directory-does-not-exist'
module = hub.Module('https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/2')
```

I think it's better to occur an error in such case.

Actually, when we try to use GCS Bucket of which we don't have the permission, it occurs an error.

### PR DESCRIPTION
**Pull request by sfujiwara**
I'm trying to fix #261 .
But I don't know how to test it and it is not written in [contribution guide](https://github.com/tensorflow/hub/blob/master/CONTRIBUTING.md).

Please advise me.

### CODE REVIEW

**Comment by akhorlin** [comment]
Thank you for looking into this issue. Couple of questions and suggestions about the proposed fix. I think it would be great to push this logic down the stack a bit. For example, we can perform the check at the place where we try to create the cache directory (https://github.com/tensorflow/hub/blob/c2ff9d4ae06fe600633694f81b859aead189754c/tensorflow_hub/resolver.py#L84). 

My guess is the hanging we see in #261 comes from the attempt to MakeDirs in a bucket that doesn't exist. So I think we also need to distinguish between two cases gs://nonexistant_bucket vs gs://bucket_exists/nonexistant_directory_within_bucket. In the second case, we should be ok because MakeDirs will be able to create a missing directory. In the first case, we go into an infinite retry loop most likely in GCS file system implementation because we cannot create a GCS bucket (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/cloud/gcs_file_system.cc).

**Comment by sfujiwara** [comment]
I found the cause of the issue.
In the case of trying to use non-existing GCS bucket, write operation fails here:

https://github.com/tensorflow/hub/blob/09f45963f6787322967b6fec61459f3ac56fbb27/tensorflow_hub/tf_utils.py#L58-L59

However, `atomic_write_string_to_file` function is called in infinite loop and the error is ignored as below:

https://github.com/tensorflow/hub/blob/09f45963f6787322967b6fec61459f3ac56fbb27/tensorflow_hub/resolver.py#L376-L387

Thus, I propose two plans to modify it.
Which do you prefer to?

### Plan 1

Raise an error here:

https://github.com/tensorflow/hub/blob/09f45963f6787322967b6fec61459f3ac56fbb27/tensorflow_hub/resolver.py#L387

### Plan 2

Catch an error using `try ... except ...` here:

https://github.com/tensorflow/hub/blob/c2ff9d4ae06fe600633694f81b859aead189754c/tensorflow_hub/tf_utils.py#L58-L59

**Comment by sfujiwara** [comment]
I fixed #261 following plan 1.
Before catching and ignoring `tf.errors.OpError`, we catch only `tf.errors.NotFoundErros` and raise it.

By this modification, we can properly treat the cases below:

- `gs://not-existing-bucket/...`
  - Raise 404 error (This is fixed by this PR)
- `gs://existing-bucket/not-existing-dir/...`
  - Automatically create dir
- `gs://not-permitted-bucket/...`
  - Raise 403 error
- `/not/existing/local/dir`
  - Automatically create dir

**Comment by sfujiwara** [comment]
@akhorlin Hi, could you review it?

**Comment by akhorlin** [comment]
I think the current approach of raising an error in resolver.py looks good. Would it possible to add a unit test (pymock atomic_write to raise an error and make sure that the error bubbles up to the caller as expected)?

**Comment by sfujiwara** [comment]
@akhorlin Hi, I added an unit test using mock. I'm not familiar with a unit test in such case, so I'm happy if you check it!

The unit test try
- Replace `tf_utils.atomic_write_string_to_file` with a mock only raising `tf.error.NotFoundError`
- Call `resolver.atomic_download` which internally use `tf_utils.atomic_write_string_to_file`
- Check if `resolver.atomic_download` raise `tf.error.NotFoundError`
  - Note that other errors are ignored

In addition, I fixed redundant way of writing as below:

```python
except tf.errors.NotFoundError as e:
    raise e

==>

except tf.errors.NotFoundError:
    raise
```

**Comment by akhorlin** [comment]
Thank you, Shuhei! The test looks good. I'll shepherd this change through our internal copy of the repo and back into GitHub. I am travelling this week, so I will run through this procedure first thing next week.

**Comment by akhorlin** [comment]
Thank you, Shuhei, for the contribution!  Your contribution was merged into master in 74999aba795845dea89bb71168aec361f9e3a46a

**Pull request closed without merging**
