### PR TITLE
Simplified the export using tf.saved_model.simple_save

### PR DESCRIPTION
**Pull request by rhaertel80**

### CODE REVIEW

**Comment by arnoegw** [comment]
Thank you, rhaertel80! I'll shepherd this through our interval copy of the repo and back into GitHub.

**Comment by arnoegw** [comment]
This was committed as https://github.com/tensorflow/hub/commit/0645b446e61e3e51e00c20a2f925111dcd29e264

**Comment by arnoegw** [comment]
More precisely, this was merged as
https://github.com/tensorflow/hub/commit/0645b446e61e3e51e00c20a2f925111dcd29e264

**Comment by rhaertel80** [comment]
Thanks! Next time I'll submit internally, instead.

**Pull request closed without merging**
