### PR TITLE
New Publisher Added - Bohemian Visual Recognition Alliance

### PR DESCRIPTION
**Pull request by picekl**

### CODE REVIEW

**Comment by j-grimstad** [comment]
Hi @picekl , since this is your first time contributing to the TFhub.dev repository, we just need you to read & agree to the TensorFlow Hub terms of service at https://tfhub.dev/terms. If you feel comfortable moving forward, please add a comment "I have read and agree to the TensorFlow Hub Terms of Service" to this thread.

**Comment by picekl** [comment]
Hi @j-grimstad.

"I have read and agree to the TensorFlow Hub Terms of Service"

**Comment by j-grimstad** [comment]
Thank you! Publishing is in process now -- I'll circle back once the model is live on the site.

**Comment by j-grimstad** [comment]
Hi @picekl , thanks again for your contributions - the assets are now live:

Model - [see here](https://tfhub.dev/bohemian-visual-recognition-alliance/models/mushroom-identification_v1/1)

Publisher page - [see here](https://tfhub.dev/bohemian-visual-recognition-alliance)

If you'd like to make edits to your assets (either now or over time), please feel free to open another PR -- please let me know if you have any questions!

**Comment by picekl** [comment]
Hi Jordan,

Thank you for helping me. I’m already working on update. 

Waiting for DOI from Christine. You can expect new pull request later today.

Best,
Lukas

**Pull request closed without merging**
