### PR TITLE
Fix minor typo in docs

### PR DESCRIPTION
**Pull request by hegdeashwin**
Changes

- [x] Fix minor typo from `thub.dev` to `tfhub.dev` in docs - `hosting.md` and `model_formats.md`.

Notes

- [x] Submitted the Google Individual Contributor License Agreement. I'm new to this process, hope I've followed it correctly. Please let me know in case I'm missing something here.

Screenshot 2020-10-25 at 6 06 47 PM

### CODE REVIEW

**Comment by maringeo** [comment]
Hi @hegdeashwin - thank you for contributing to TensorFlow Hub!

The changes in this PR look good. 

The google-cla check must pass before merging this PR. You've signed the CLA but the commit https://github.com/hegdeashwin/hub/commit/e5758d892c349f6116309f870f5d9f21b9798de4 is not linked to your GitHub account. I think this guide https://help.github.jp/enterprise/2.11/user/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user might help resolve the problem.

**Comment by hegdeashwin** [comment]
@googlebot I fixed it.

**Comment by maringeo** [comment]
Thanks @hegdeashwin, the last step is to change this commit https://github.com/hegdeashwin/hub/commit/e5758d892c349f6116309f870f5d9f21b9798de4 to be associated with your GitHub email.

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History describes how do this (since the commit in question is the last commit in your forked repository you can use `git commit --amend` instead of the more complicated interactive rebase `git rebase -i`).

**Comment by hegdeashwin** [comment]
Yay it worked like a charm 👍

**Comment by maringeo** [comment]
Thanks @hegdeashwin, this PR has been merged in af2e11a017a764944b783c3fd97f4790f93958ac. The changes will be pushed to tensorflow.org/hub in the next 24 hours.

**Pull request closed without merging**
