### PR TITLE
Added model file.

### PR DESCRIPTION
**Pull request by see--**
This PR adds the model from: https://github.com/see--/natural-question-answering as Saved Model.

### CODE REVIEW

**Comment by vbardiovskyg** [comment]
Thanks for your contribution!

Two things before we can accept your pull request:

1) Instead of submitting under the Kaggle publisher, please create your own publisher page with your GitHub handle instead, i.e. change "kaggle" to "see--". I am going to update the documentation soon to reflect this.

2) Prior to accepting your pull request, we just need you to read & agree to the TensorFlow Hub terms of service at https://tfhub.dev/terms. If you feel comfortable moving forward, please add a comment "I have read and agree to the TensorFlow Hub Terms of Service" to this thread.

Let us know if you have any questions and thanks!

**Comment by vbardiovskyg** [comment]
I edited the point (1) in the comment above, so just making sure you noticed.

**Comment by see--** [comment]
Thanks for your help.

1. I updated the publisher to my GitHub handle "see--".
2. I have read and agree to the TensorFlow Hub Terms of Service

**Comment by vbardiovskyg** [comment]
Your model is now live: https://tfhub.dev/see--/bert-uncased-tf2-qa/1, thanks for contributing!

**Comment by DesiKeki** [comment]
Hi @see-- , @vbardiovskyg ,
I get the following error while using this model:

```
----> 5 tokenizer = BertTokenizer.from_pretrained('tokenizer_tf2_qa')

OSError: Can't load tokenizer for 'tokenizer_tf2_qa'. Make sure that:

- 'tokenizer_tf2_qa' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'tokenizer_tf2_qa' is the correct path to a directory containing relevant tokenizer files
```

Any pointers to what I might be missing?

**Comment by see--** [comment]
> - or 'tokenizer_tf2_qa' is the correct path to a directory containing relevant tokenizer files

You can download the tokenizer from my repo.

**Comment by DesiKeki** [comment]
Thanks @see-- 
I did the following:

```
os.system('wget https://github.com/see--/natural-question-answering/releases/download/v0.0.1/tokenizer_tf2_qa.zip')
os.system('unzip tokenizer_tf2_qa.zip')
tokenizer = BertTokenizer.from_pretrained('tokenizer_tf2_qa')
```

And now I am getting following error:
`AssertionError: Non-consecutive added token 'td_colspan' found. Should have index 30522 but has index 1 in saved vocabulary.
`
Please let me know how can I resolve this?

**Comment by see--** [comment]
You can install transformers from my repo. It looks like your version is not compatible.

**Comment by DesiKeki** [comment]
> You can install transformers from my repo. It looks like your version is not compatible.

Can you please guide on how to do that?
Your repo says "This repo is tested on Python 3.5+, PyTorch 1.0.0+ and TensorFlow 2.0.0-rc1"
So should I go to these versions? How to install transformers from your repo after that?

**Comment by see--** [comment]
Just follow the [README](https://github.com/see--/natural-question-answering/blob/master/README.md). Feel free to open an issue in my repo if you think something is missing.

**Comment by DesiKeki** [comment]
@see-- it worked! Thanks a lot 👍

**Pull request closed without merging**
