### PR TITLE
Adding int8 and float16 quantized TF lite models for DeepLab (COCO)

### PR DESCRIPTION
**Pull request by sayakpaul**
A brief description of the previous TF Lite model is available [here](https://github.com/tensorflow/hub/blob/master/tfhub_dev/assets/sayakpaul/deeplabv3-mobilenetv2/default/lite/1.md). This PR adds int8 and float16 TF Lite models that allow us to take advantage of the hardware accelerators supported by TF Lite.

### CODE REVIEW

**Comment by sayakpaul** [comment]
@maringeo not sure why this particular error is popping up again:

```
__main__.MarkdownDocumentationError: Error at file /home/runner/work/hub/hub/tfhub_dev/assets/sayakpaul/deeplabv3-mobilenetv2-int8/1.md: There are missing required metadata lines. Please refer to README.md for information about markdown format. **In particular the missing metadata are: ['fine-tunable', 'module-type']
##[error]Process completed with exit code 123**.
```

As far as you had told last time, for TF Lite models, these tags are not necessary to provide. Am I missing out on something?

**Comment by sayakpaul** [comment]
@kempy the pipeline fails because of the reasons shown [here](https://github.com/tensorflow/hub/pull/629/checks?check_run_id=833521313). I thought those metadata tags weren't required as mentioned by @maringeo in our previous conversations.

**Comment by maringeo** [comment]
Thanks @sayakpaul for contributing to TF Hub! I've started the model import process and will let you know once the models are available on tfhub.dev. Please ignore the validator test failure - the fix for the invalid assertion will soon be pushed to the repo.

**Comment by sayakpaul** [comment]
Sounds good @maringeo. Thank you :)

**Comment by maringeo** [comment]
Thanks! Your contribution has been merged in https://github.com/tensorflow/hub/commit/21c329bbafaf22dc82b971a0ab742cf028a139db

The models are live on tfhub.dev:
https://tfhub.dev/sayakpaul/lite-model/deeplabv3-mobilenetv2-int8/1/default/1
https://tfhub.dev/sayakpaul/lite-model/deeplabv3-mobilenetv2-float16/1/default/1

**Comment by sayakpaul** [comment]
@khanhlvg FYI.

**Pull request closed without merging**
