### PR TITLE
AgriPredict model submission

### PR DESCRIPTION
**Pull request by mwizasimbeye11**

### CODE REVIEW

**Comment by mwizasimbeye11** [comment]
@googlebot I signed it!

**Comment by mwizasimbeye11** [comment]
@googlebot I signed it!

**Comment by mwizasimbeye11** [comment]
@googlebot I signed it!

**Comment by mwizasimbeye11** [comment]
@googlebot I signed it!

**Comment by WGierke** [comment]
Hi @mwizasimbeye11, the PR looks good now.

Since this is your first time contributing to the TFhub.dev repository, we just need you to read & agree to the TensorFlow Hub terms of service at https://tfhub.dev/terms. If you feel comfortable moving forward, please add a comment "I have read and agree to the TensorFlow Hub Terms of Service" to this thread.

**Comment by mwizasimbeye11** [comment]
I have read and agree to the TensorFlow Hub Terms of Service

**Comment by WGierke** [comment]
Hi @mwizasimbeye11 , thanks for your contribution! I merged it into master via e3dda27bea84aeac9cc95f38eeebbef492167215.

**Pull request closed without merging**
