### PR TITLE
Changes checkpoints_dir to checkpoint_path in parser args

### PR DESCRIPTION
**Pull request by skvrahul**
Makes changes to the parser argument name as requested by the maintainers in tensorflow#307
Original PR made by @junxnone

### CODE REVIEW

**Comment by junxnone** [comment]
it is ok for me

**Comment by junxnone** [comment]
thanks

**Comment by arnoegw** [comment]
@junxnone has signed a CLA, as seen on https://github.com/tensorflow/hub/pull/307

**Comment by arnoegw** [comment]
Thank you, @skvrahul and @junxnone! This looks good to me. I'll shepherd it through our internal repo and back out again to github,

**Comment by arnoegw** [comment]
This has been puhsed to master in commit https://github.com/tensorflow/hub/commit/6ffb843c32b6d5f846dbc4778f1ef10c0f01ce53

Thank you again!

**Pull request closed without merging**
